spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
      prod:
        - db-aws
      docker-local:
        - db-docker-local
    include:
      - db

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
server:
  port: 8080



